const ApiConstants = {
  UPDATE_LOADING_STATE: 'UPDATE_LOADING_STATE',

  API_GET_PRODUCT_LIST_LOAD: 'API_GET_PRODUCT_LIST_LOAD',
  API_GET_PRODUCT_LIST_SUCCESS: 'API_GET_PRODUCT_LIST_SUCCESS',

  API_GET_PRODUCT_DETAILS_LOAD: 'API_GET_PRODUCT_DETAILS_LOAD',
  API_GET_PRODUCT_DETAILS_SUCCESS: 'API_GET_PRODUCT_DETAILS_SUCCESS',

  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEMS: "REMOVE_ITEMS"
};
export default ApiConstants;
